language: go
go:
- 1.13.7
go_import_path: github.com/cisco-sso/kdk
services:
- docker
before_install:
- sudo /etc/docker/daemon.json
- make checks
script:
- make bin-build docker-build
deploy:
- true:
    tags: true
  provider: script
  script:
  - make docker-push bin-push
  skip_cleanup: true
dist: focal
